pollingsite/pollingsite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

pollingsite/polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/add/
    url(r'^add/$', views.add, name='add'),
    # ex: /polls/save/
    url(r'^save/$', views.save, name='save'),
    # ex: /polls/login/
    url(r'^login/$', views.login, name='login'),
    # ex: /polls/login_post/
    url(r'^login_post/$', views.login_post, name='login_post'),
    # ex: /polls/signup/
    url(r'^signup/$', views.signup, name='signup'),
    # ex: /polls/signup_post/
    url(r'^signup_post/$', views.signup_post, name='signup_post'),
    # ex: /polls/logout/
    url(r'^logout/$', views.logout, name='logout'),
    
)

pollingsite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Member(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    def __unicode__(self):
        return self.username

class Poll(models.Model):
    question = models.CharField(max_length=200)
    author = models.ForeignKey(Member)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

pollingsite/polls/views.py
from django.shortcuts import render
from polls.models import Choice, Poll

def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:5]
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)

def detail(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def vote(request, poll_id):
    poll = Poll.objects.get(id=poll_id)
    if 'choice' not in request.POST: # User didn't make a choice
        return detail(request, poll_id)
    else:
        selected_choice = poll.choice_set.get(id=request.POST['choice'])
        selected_choice.votes += 1
        selected_choice.save()
        return index(request)

pollingsite/polls/templates/polls/add.html
<h1>New Poll</h1>

<form action="{% url 'polls:save' %}" method="post">
{% csrf_token %}
	Question: <input type="text" name="question" /><br />
	Choice 1: <input type="text" name="choice1" /><br />
	Choice 2: <input type="text" name="choice2" /><br />
	Choice 3: <input type="text" name="choice3" /><br />
<input type="submit" value="Add Poll" />
</form>
<a href="{% url 'polls:index' %}">Home</a>

pollingsite/polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

pollingsite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>Polls</h1>

{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:add' %}">Add a new poll</a>

pollingsite/polls/templates/polls/login.html
<h1>Login Page</h1>

<h3>{{ error_message }}</h3>

<form action="{% url 'polls:login_post' %}" method="post">
{% csrf_token %}
	Username: <input type="text" name="username" /><br />
	Password: <input type="password" name="password" /><br />
	<input type="submit" value="Login" />
</form>

pollingsite/polls/templates/polls/results.html
<h1>Results</h1>

<ul>
{% for choice in poll.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} votes</li>
{% endfor %}
</ul>
<a href="{% url 'polls:index' %}">Home</a>

pollingsite/polls/templates/polls/signup.html
<h1>Signup Page</h1>

<h3>{{ error_message }}</h3>

<form action="{% url 'polls:signup_post' %}" method="post">
{% csrf_token %}
	Username: <input type="text" name="username" /><br />
	Password: <input type="password" name="password0" /><br />
	Retype Password: <input type="password" name="password1" /><br />
	<input type="submit" value="Sign up" />
</form>